### ISSUE TITLE
Error in the example configuration

### ISSUE THREAD

**Issue by Vfisa** [keboola/processor-fit-into-storage#2]
This default config generates an error during run:
```
{
    "definition": {
        "component": "keboola.processor-fit-into-storage"
    },
    "parameters": {
        "chunk_size": "900000"
    }
}
```
Error: 

> Invalid type for path "root.parameters.chunk_size". Expected int, but got string.

Therefore I suggest the correct one should be:
```
{
    "definition": {
        "component": "keboola.processor-fit-into-storage"
    },
    "parameters": {
        "chunk_size": 900000
    }
}
```

**Comment by odinuv** [comment]
thanks for reporting, fixed in https://github.com/keboola/processor-fit-into-storage/commit/ec6077e0ca29fb936dec5f467640ca19eda10c0d
